# Generated by Django 5.2.4 on 2025-08-01 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('GOVT', 'GOVT'), ('SWAP', 'SWAP'), ('CORP', 'CORP')], default='GOVT', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('iso_code', models.CharField(choices=[('PLN', 'PLN'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('CAD', 'CAD'), ('AUD', 'AUD'), ('JPY', 'JPY'), ('CHF', 'CHF'), ('CNY', 'CNY'), ('SEK', 'SEK'), ('NZD', 'NZD')], default='PLN', max_length=3)),
                ('currency', models.CharField(max_length=3)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='curvecalc.country')),
            ],
            options={
                'unique_together': {('type_name', 'iso_code', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='Tenors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('tenor_6m', models.FloatField(blank=True, max_length=7, null=True)),
                ('tenor_1y', models.FloatField(blank=True, max_length=7, null=True)),
                ('tenor_2y', models.FloatField(blank=True, max_length=7, null=True)),
                ('tenor_5y', models.FloatField(blank=True, max_length=7, null=True)),
                ('tenor_7y', models.FloatField(blank=True, max_length=7, null=True)),
                ('tenor_10y', models.FloatField(blank=True, max_length=7, null=True)),
                ('type_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenors', to='curvecalc.type')),
            ],
        ),
    ]
