# Generated by Django 5.2.4 on 2025-08-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curvecalc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tenors',
            new_name='Tenor',
        ),
    ]
