# Generated by Django 5.2.4 on 2025-08-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curvecalc', '0002_rename_tenors_tenor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenor',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
