# Generated by Django 5.2.4 on 2025-08-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curvecalc', '0003_alter_tenor_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type_name',
            field=models.TextField(choices=[('GOVT', 'GOVT'), ('SWAP', 'SWAP'), ('CORP', 'CORP')], default='GOVT', max_length=20),
        ),
    ]
