# Generated by Django 5.2.4 on 2025-08-07 19:57

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('isin', models.CharField(max_length=12, unique=True)),
                ('coupon_rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('coupon_frequency', models.PositiveSmallIntegerField(max_length=2)),
                ('maturity_date', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2025, 8, 8))])),
                ('redemption_price', models.DecimalField(decimal_places=4, max_digits=7)),
                ('currency', models.CharField(max_length=3)),
                ('has_call_option', models.BooleanField(default=False)),
                ('call_price', models.DecimalField(decimal_places=4, max_digits=7)),
                ('call_date', models.DateField(verbose_name='Call Date')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Bond',
                'verbose_name_plural': 'Bonds',
                'ordering': ['maturity_date'],
                'unique_together': {('name', 'isin')},
            },
        ),
    ]
