# Generated by Django 5.2.4 on 2025-08-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonddb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='coupon_frequency',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Coupon Frequency (times per year)'),
        ),
    ]
